ProSum/Models/Announcement.cs
using System;

namespace ProSum.Models
{
    public class Announcement
    {
        public Guid AnnouncementId { get; set; }
        public Guid ProjectId { get; set; }
        public Guid AuthorId { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public DateTime Timestamp { get; set; }
        public User Author { get; set; }
        public Announcement(Guid projectId, Guid userId, string title, string message)
        {
            AnnouncementId = Guid.NewGuid();
            ProjectId = projectId;
            AuthorId = userId;
            Title = title;
            Message = message;
        }

        public Announcement()
        {

        }
    }
}

ProSum/Models/Project.cs
using System;
using System.Collections.Generic;

namespace ProSum.Models
{
    public class Project
    {
        public Guid Id { get; set; }

        private string title;
        public string Title
        {
            get
            {
                return title;
            }
            set
            {
                if (value.Length > 0)
                {
                    title = value;
                }
            }

        }
        private DateTime deadline;
        public DateTime Deadline
        {
            get
            {
                return deadline;
            }
            set
            {
                if (value != null)
                {
                    if (value > DateTime.Now)
                    {
                        deadline = value;
                    }

                }
            }
        }

        private string description;
        public string Description
        {
            get
            {
                return description;
            }
            set
            {
                description = value;
            }
        }

        public List<ProjectStep> Steps { get; set; }
        public Guid ClientId { get; set; }
        public List<User> ProjectManagers { get; set; }

        public Client Client { get; set; }
        public Project() { }

        public Project(string title, DateTime deadline, string description, Guid clientId)
        {
            Id = Guid.NewGuid();
            Title = title;
            Deadline = deadline;
            Description = description;
            ClientId = clientId;
            ProjectManagers = new List<User>();
        }
    }
}

ProSum/Models/ViewModels/AnnouncementViewModel.cs
using System;
using System.Collections.Generic;

namespace ProSum.Models.ViewModels
{
    public class AnnouncementViewModel
    {
        public Guid ProjectId { get; set; }
        public List<Announcement> Announcements { get; set; }
        public List<ProjectFile> ProjectFiles { get; set; }
    }
}

ProSum/Models/ViewModels/ProjectViewModel.cs
using System;
using System.Collections.Generic;

namespace ProSum.Models.ViewModels
{
    public class ProjectViewModel
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public List<User> ProjectManagers { get; set; }
        public DateTime DeadLine { get; set; }
        public List<ProjectStep> Steps { get; set; }
        public Client Client { get; set; }
        public List<Permission> UserPermissions { get; set; }
        public List<User> ProjectEmployees { get; set; }
        public List<Announcement> Announcements { get; set; }
    }
}

ProSum/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProSum.Containers.Interfaces;
using ProSum.Models;
using ProSum.Models.ViewModels;
using ProSum.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ProSum.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IProjectService _ProjectService;
        private readonly IUserService _userService;
        private readonly ISessionContainer _SessionContainer;
        private readonly IHttpContextAccessor _ContextAccessor;
        private readonly IPermissionContainer _permissionContainer;
        private readonly IClientService _ClientService;
        private readonly ILogger _Logger;
        private readonly IStepContainer _StepContainer;
        private readonly IAnnouncementContainer _AnnouncementContainer;
        private readonly IProjectFileContainer _ProjectFileContainer;

        public ProjectController(
            IProjectService projectService,
            IHttpContextAccessor contextAccessor,
            ISessionContainer sessionContainer,
            IUserService userService,
            IPermissionContainer permissionContainer,
            IClientService clientService,
            IStepContainer stepContainer,
            ILogger logger,
            IAnnouncementContainer announcementContainer,
            IProjectFileContainer projectFileContainer)
        {
            _ProjectService = projectService;
            _SessionContainer = sessionContainer;
            _ContextAccessor = contextAccessor;
            _userService = userService;
            _permissionContainer = permissionContainer;
            _ClientService = clientService;
            _StepContainer = stepContainer;
            _Logger = logger;
            _AnnouncementContainer = announcementContainer;
            _ProjectFileContainer = projectFileContainer;
        }

        // /project/
        [HttpGet]
        public IActionResult Index()
        {
            // Project overview
            List<ProjectViewModel> model = new List<ProjectViewModel>();

            List<Project> projects = _ProjectService.Get();

            foreach (Project project in projects)
            {
                model.Add(new ProjectViewModel()
                {
                    Id = project.Id,
                    Title = project.Title,
                    Description = project.Description,
                    DeadLine = project.Deadline,
                    ProjectManagers = project.ProjectManagers,
                    Steps = project.Steps.OrderBy(step => step.Step.StepNumber).ToList(),
                    Client = project.Client
                });
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult AddEmployee(Guid projectId)
        {
            if (_SessionContainer.IsLoggedIn(_ContextAccessor))
            {
                if (!_SessionContainer.HasAccess(_ContextAccessor, new RolesEnum[] { RolesEnum.Manager }))
                {
                    return RedirectToAction("AccessDenied", "Permission");
                }
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnUrl = $"/Project/AddEmployee?projectId={projectId}" });
            }


            ProjectAddEmployee model = new ProjectAddEmployee();
            model.ProjectId = _ProjectService.Get(projectId).Id;
            model.ProjectEmployees = _ProjectService.GetAllUsersInProject(projectId);
            List<User> allEmployees = _userService.GetAllWithRole(RolesEnum.Employee);
            allEmployees.AddRange(_userService.GetAllWithRole(RolesEnum.Manager));
            List<User> employeesNotInProject = new List<User>();

            foreach (User employee in allEmployees)
            {
                if (!model.ProjectEmployees.Any(u => u.Id == employee.Id))
                {
                    employeesNotInProject.Add(employee);
                }
            }

            model.Employees = employeesNotInProject;

            return View(model);
        }

        [HttpPost]
        public IActionResult AddEmployee(ProjectAddEmployee data)
        {
            Project project = _ProjectService.Get(data.ProjectId);
            if (_SessionContainer.IsLoggedIn(_ContextAccessor))
            {
                if (!_SessionContainer.IsProjectManager(_ContextAccessor, project))
                {
                    return RedirectToAction("AccessDenied", "Permission");
                }
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnUrl = $"/Project/AddEmployee?projectId={data.ProjectId}" });
            }

            if (ModelState.IsValid)
            {
                if (data.IsProjectLeader)
                {
                    _ProjectService.AddProjectPermission(
                    _ProjectService.Get(data.ProjectId),
                    _userService.Get(data.NewEmployeeId),
                    _permissionContainer.Permissions.FirstOrDefault(p => p.Name == "ProjectManager")
                    );
                }
                else
                {
                    _ProjectService.AddProjectPermission(
                        _ProjectService.Get(data.ProjectId),
                        _userService.Get(data.NewEmployeeId),
                        _permissionContainer.Permissions.FirstOrDefault(p => p.Name == "ProjectEmployee"));
                }


                _Logger.Log(_SessionContainer.GetSession(_ContextAccessor).User.Id, data.ProjectId, LogEntryUpdateType.UPDATED_USER_PERMISSIONS, data.NewEmployeeId);
                return RedirectToAction(nameof(ProjectController.EditEmployeePermission), new { userId = data.NewEmployeeId, projectId = data.ProjectId });

            }
            else
            {
                List<User> allEmployees = _userService.GetAllWithRole(RolesEnum.Employee);
                List<User> employeesNotInProject = new List<User>();
                data.ProjectEmployees = _ProjectService.GetAllUsersInProject(data.ProjectId);

                foreach (User employee in allEmployees)
                {
                    if (!data.ProjectEmployees.Any(u => u.Id == employee.Id))
                    {
                        employeesNotInProject.Add(employee);
                    }
                }

                data.Employees = employeesNotInProject;
                return View(data);
            }
        }

        [HttpGet]
        public IActionResult EditEmployeePermission(Guid userId, Guid projectId)
        {
            Project project = _ProjectService.Get(projectId);
            if (_SessionContainer.IsLoggedIn(_ContextAccessor))
            {
                if (!_SessionContainer.IsProjectManager(_ContextAccessor, project))
                {
                    return RedirectToAction("AccessDenied", "Permission");
                }
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnUrl = $"/Project/EditEmployeePermission?userId={userId}&projectId={projectId}" });
            }

            PermissionViewModel model = new PermissionViewModel()
            {
                UserId = userId,
                ProjectId = projectId
            };

            List<Step> steps = _StepContainer.Steps.ToList();
            List<StepPermission> stepPermissions = new List<StepPermission>();
            foreach (Step step in steps)
            {
                stepPermissions.Add(new StepPermission()
                {
                    Step = step
                });
            }

            model.Permissions = stepPermissions.OrderBy(p => p.Step.StepNumber).ToList();

            User user = _userService.Get(userId);
            _ProjectService.GetProjectPermissions(user);

            model.CurrentPermissions = user.GetProjectPermission(projectId);
            model.IsProjectLeader = user.GetProjectPermission(projectId).HasPermission("ProjectManager");
            return View(model);
        }

        [HttpPost]
        public IActionResult EditEmployeePermission(PermissionViewModel data)
        {
            Project project = _ProjectService.Get(data.ProjectId);
            if (_SessionContainer.IsLoggedIn(_ContextAccessor))
            {
                if (!_SessionContainer.IsProjectManager(_ContextAccessor, project))
                {
                    return RedirectToAction("AccessDenied", "Permission");
                }
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnUrl = $"/Project/EditEmployeePermission?userId={data.UserId}&projectId={data.ProjectId}" });
            }

            User user = _userService.Get(data.UserId);
            _ProjectService.GetProjectPermissions(user);

            if (user.GetProjectPermission(project.Id) != null)
            {
                foreach (Step step in _StepContainer.Steps)
                {
                    if (user.GetProjectPermission(project.Id).HasPermission("Read" + step.Name))
                    {
                        _ProjectService.RemoveProjectPermission(
                            project,
                            _userService.Get(data.UserId),
                            _permissionContainer.Permissions.FirstOrDefault(p => p.Name == "Read" + step.Name));
                    }

                    if (user.GetProjectPermission(project.Id).HasPermission("Write" + step.Name))
                    {
                        _ProjectService.RemoveProjectPermission(
                            project,
                            _userService.Get(data.UserId),
                            _permissionContainer.Permissions.FirstOrDefault(p => p.Name == "Write" + step.Name));
                    }
                }
            }

ProSum/Views/Project/AddAnnouncement.cshtml
@model ProSum.Models.ViewModels.CreateAnnouncementViewModel
@{
    ViewData["Title"] = "AddAnnouncement";
}

<div class="body-content">
    <form asp-action="AddAnnouncement" asp-controller="Project">
        <div class="form-group">
            <span asp-validation-for="@Model.Title" class="text-danger"></span> <br />
            <label asp-for="@Model.Title" class="control-label">Titel: </label>
            <input type="text" asp-for="@Model.Title" class="form-control" />
        </div>
        <div class="form-group">
            <span asp-validation-for="@Model.Message" class="text-danger"></span> <br />
            <label asp-for="@Model.Message" class="control-label">Bericht: </label>
            <input type="text" asp-for="@Model.Message" class="form-control" />
        </div>
        <div class="form-group">
            <input type="hidden" asp-for="@Model.ProjectId" value="@Model.ProjectId" />
            <input type="submit" value="Voeg toe" class="btn btn-success" />
        </div>
    </form>
</div>

ProSum/Views/Project/AddEmployee.cshtml
@using ProSum.Models.ViewModels
@model ProjectAddEmployee
@{
    ViewData["Title"] = "AddEmployees";
}

<h1>Medewerker toevoegen</h1>
<div class="body-content">
    <form asp-action="AddEmployee" asp-controller="Project" asp-route-projectId="@Model.ProjectId">
        <div class="form-group">
            <span asp-validation-for="@Model.NewEmployeeId" class="text-danger"></span> <br />

            <label for="employee">Nieuwe medewerker</label>
            <select class="form-control" asp-for="@Model.NewEmployeeId">
                @foreach (User employee in Model.Employees)
                {
                    <option value="@employee.Id">@employee.Name</option>
                }
            </select>
        </div>
        <input type="submit" value="Toevoegen" class="ml-0 btn btn-success" />
    </form>

    


    <h2>Project Medewerkers:</h2>
    <table class="table table-responsive">
        <tr>
            <th>
                Naam:
            </th>
            <th>
                Email:
            </th>
            <th>
                Telefoonnummer:
            </th>
            <th>
                Edit
            </th>
        </tr>
        @foreach (User projectEmployee in Model.ProjectEmployees)
        {
            <tr>
                <td>
                    @projectEmployee.Name
                </td>
                <td>
                    @projectEmployee.Email
                </td>
                <td>
                    @projectEmployee.PhoneNumber
                </td>
                <td>
                    <form asp-controller="Project" asp-action="EditEmployeePermission" method="get">
                        <input type="hidden" value="@projectEmployee.Id" name="userId" />
                        <input type="hidden" value="@Model.ProjectId" name="projectId" />
                        <button type="submit" class="btn btn-success">Edit</button>
                    </form>
                </td>
            </tr>
        }
    </table>
</div>

@section Scripts {
    <script type="text/javascript">
        $("#inputUserName").on("change keydown input paste", function () {
            var selectedOption = $("#employees option[value='" + $(this).val() + "']");
            var selectedUser = selectedOption.attr('data-userId');

            if (selectedUser) {
                $('#UserId').val(selectedUser);
            } else {
                console.log("No value");
                $('#UserId').val('');
            }
        })
    </script>}

ProSum/Views/Project/AddProjectFile.cshtml
@model ProSum.Models.ViewModels.CreateFileViewModel
@{
    ViewData["Title"] = "AddProjectFile";
}

<div class="body-content">
    <form asp-action="AddProjectFile" asp-controller="Project">
        <div class="form-group">
            <span asp-validation-for="@Model.Title" class="text-danger"></span> <br />
            <label asp-for="@Model.Title" class="control-label">Titel: </label>
            <input type="text" asp-for="@Model.Title" class="form-control" />
        </div>
        <div class="form-group">
            <span asp-validation-for="@Model.Link" class="text-danger"></span> <br />
            <label asp-for="@Model.Link" class="control-label">Link: </label>
            <input type="text" asp-for="@Model.Link" class="form-control" />
        </div>
        <div class="form-group">
            <span asp-validation-for="@Model.Department" class="text-danger"></span> <br />
            <label asp-for="@Model.Department" class="control-label">Department: </label>
            <select class="form-control" asp-for="@Model.Department" asp-items="@Html.GetEnumSelectList(typeof(DepartmentEnum))"></select>
        </div>
        <div class="form-group">
            <input type="hidden" asp-for="@Model.ProjectId" value="@Model.ProjectId" />
        </div>
        <button type="submit" class="btn btn-success">Add file!</button>
    </form>
</div>

ProSum/Views/Project/Announcements.cshtml
@using ProSum.Models.ViewModels
@model AnnouncementViewModel
@{
    ViewData["Title"] = "Announcements";
}


@section Styles { <link rel="stylesheet" href="~/css/ProjectDetailPage.css" /> }

<div class="body-content">
    <h1>Project</h1>
    <header>
        <nav class="navbar">
            <a class="navbar-text" asp-action="Details" asp-controller="Project" asp-route-projectId="@Model.ProjectId">Details</a>
            <a class="navbar-text" style="color:gray; text-decoration:underline;" href="#">Announcements (@Model.Announcements.Count)</a>
        </nav>
    </header>

    <div class="project-wrapper">
        <div class="project-column-wrapper">
            <div class="container">
                <h2>Files</h2>
                <table class="table-responsive table-bordered">
                    <thead>
                        <tr>
                            <th>Title:</th>
                            <th>Location:</th>
                            <th>Department:</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.ProjectFiles != null && Model.ProjectFiles.Count > 0)
                        {
                            @foreach (ProjectFile file in Model.ProjectFiles)
                            {
                                <tr>
                                    <td><a href=@file.Link target="_blank">@file.Link</a></td>
                                    <td>@file.Title</td>
                                    <td>@file.Department</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
                <div style="margin-top:10px;">
                    <form asp-controller="Project" asp-action="AddProjectFile" method="get" style="margin-right: 20px;">
                        <input type="hidden" name="projectId" value="@Model.ProjectId" />
                        <button class="btn btn-primary">Nieuw Bestand Toevoegen</button>
                    </form>
                </div>
                <br />
                <hr />
                <h2>Announcements</h2>
                @if (Model.Announcements != null && Model.Announcements.Count > 0)
                {
                    @foreach (Announcement announcement in Model.Announcements.OrderByDescending(a => a.Timestamp))
                    {
                        <div class="row" style="margin-top: 10px; background-color: white; border: 1px solid lightgray; border-radius: 15px;">
                            <div class="col-sm-8">
                                <div style="font-size:25px; font-weight:bold; color: black">@announcement.Title</div>
                                <div style="font-size:18px;">@announcement.Message</div>
                                <div style="font-size:12px;"> By @announcement.Author.Name</div>
                            </div>
                            <div class="col-sm-4">
                                <div style="color:black; margin-top: 10px;">Posted on:</div>
                                <div>@announcement.Timestamp.ToString("dd MMMM yyyy HH:mm")</div>
                            </div>
                        </div>
                    }
                }
                <div style="margin-top:10px;">
                    <form asp-controller="Project" asp-action="AddAnnouncement" method="get" style="margin-right: 20px;">
                        <input type="hidden" name="projectId" value="@Model.ProjectId" />
                        <button class="btn btn-primary">Nieuwe Announcement</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

ProSum/Views/Project/Create.cshtml
@using ProSum.Models;
@using ProSum.Models.ViewModels;
@model CreateProjectViewModel;
@{
    ViewData["Title"] = "Create";
}

<div class="body-content">
    <form asp-action="Create" asp-controller="Project">
        <div class="form-group">
            <span asp-validation-for="@Model.Client" class="text-danger"></span> <br />
            <label asp-for="@Model.Client" class="control-label">Klant: </label>
            <select class="form-control" asp-for="@Model.Client">
                @foreach (Client client in Model.Clients)
                {
                    <option value="@client.Id">@client.Name</option>
                }
            </select>
        </div>

        
        <a role="button" class="btn btn-primary" style="color: white;" asp-controller="Client" asp-action="Create" asp-route-returnUrl="/Project/Create">Voeg client toe</a>
        <div class="form-group">
            <span asp-validation-for="@Model.Title" class="text-danger"></span> <br />
            <label asp-for="@Model.Title" class="control-label">Naam: </label>
            <input type="text" asp-for="@Model.Title" class="form-control" />
        </div>
        <div class="form-group">
            <span asp-validation-for="@Model.Description"  class="text-danger"></span> <br />
            <label asp-for="@Model.Description" class="control-label">Omschrijving: </label>
            <input type="text" asp-for="@Model.Description" class="form-control" />
        </div>
        <div class="form-group">
            <span asp-validation-for="@Model.DeadLine" class="text-danger"></span> <br />
            <label asp-for="@Model.DeadLine" class="control-label">Deadline: </label>
            <input type="date" asp-for="@Model.DeadLine" class="form-control" value=@DateTime.Now />
        </div>
        <div class="form-group">
            <input type="submit" value="Toevoegen" class="btn btn-primary" />
        </div>
    </form>
</div>

ProSum/Views/Project/Edit.cshtml
@using ProSum.Models.ViewModels;
@model EditProjectViewModel;
@{
    ViewData["Title"] = "Edit";
}

<div class="container" style="margin-top: 25px;">
    <form asp-action="Edit" method="post" style="width:100%">
        <div class="form-group">
            <label asp-for="@Model.Title" class="control-label">Titel: </label><br />
            <input type="text" asp-for="@Model.Title" class="form-control" style="width:100%; text-align:left; padding:0.375rem 0.75rem;color:#0d0d0d" />
        </div>
        <div class="form-group">
            <label asp-for="@Model.Description" class="control-label">Omschrijving: </label><br />
            <input type="text" asp-for="@Model.Description" class="form-control" style="width:100%; text-align:left; padding:0.375rem 0.75rem;color:#0d0d0d" />
        </div>
        <div class="form-group">
            <label asp-for="@Model.DeadLine" class="control-label">Deadline: </label>
            <input type="date" asp-for="@Model.DeadLine" class="form-control" style="width: 100%;text-align: left;color: #0d0d0d" />
        </div>
        <div class="form-group">
            <span asp-validation-for="@Model.Client" class="text-danger"></span> <br />

            <label asp-for="@Model.Client" class="control-label">Klant: </label>
            <input type="text" class="form-control validateOnDatalist" id="inputClientName" list="clients" autocomplete="off" value="" style="width:100%; text-align:left; padding:0.375rem 0.75rem; color:#0d0d0d" />
            <input type="hidden" id="clientId" class="hiddenVal" asp-for="@Model.Client" />
        </div>

        <datalist id="clients">
            @foreach (Client client in Model.Clients)
            {
                <option data-clientId="@client.Id" value="@client.Company">@client.Company</option>
            }
        </datalist>


        <div class="form-group">
            <input hidden="hidden" asp-for="@Model.Id" />
            <input type="submit" value="Bewerk" class="btn btn-primary" />
        </div>
    </form>
</div>

@section Scripts {
    <script type="text/javascript">
        $("#inputClientName").on("change keydown input paste", function () {
            var selectedOption = $("#clients option[value='" + $(this).val() + "']");
            var selectedClient = selectedOption.attr('data-clientId');

            if (selectedClient) {
                $('#clientId').val(selectedClient);
            } else {
                console.log("No value");
                $('#clientId').val('');
            }
        })
    </script>
}

ProSum/Views/Project/EditEmployeePermission.cshtml
@using ProSum.Models;
@model ProSum.Models.ViewModels.PermissionViewModel;
@{
    ViewData["Title"] = "EditPermission";
}

<div class="container">
<h1>Rechten aanpassen</h1>

    <h3>
        De lees rechten zijn voor het zien van de bijbehorende bestanden. <br />
        De schrijf rechten zijn voor het aanpassen van de status van de stap.
    </h3>
<form asp-action="EditEmployeePermission" asp-controller="Project">
    <input type="hidden" asp-for="UserId" value="@Model.UserId" />
    <input type="hidden" asp-for="ProjectId" value="@Model.ProjectId" />
    <table class="permission-table">
        <thead>
            <tr>
                <td>Stap</td>
                <td>Rechten</td>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Permissions.Count; i++)
            {
                <tr>
                    <td>
                        <input type="hidden" asp-for="@Model.Permissions[i].Step.Name" value="@Model.Permissions[i].Step.Name" />
                        @Model.Permissions[i].Step.Name
                    </td>
                    <td>
                        <div class="radio-group">

                            <input asp-for="@Model.Permissions[i].Permission" type="radio" value="@StepPermission.PermissionEnum.None" id="option-one-@(i)">
                            <label class="permission-label" for="option-one-@(i)">Geen</label>

                            @if (Model.CurrentPermissions != null && Model.CurrentPermissions.HasPermission("Read" + Model.Permissions[i].Step.Name))
                            {
                                <input asp-for="@Model.Permissions[i].Permission" type="radio" value="@StepPermission.PermissionEnum.Read" id="option-two-@(i)" checked />
                            }
                            else
                            {
                                <input asp-for="@Model.Permissions[i].Permission" type="radio" value="@StepPermission.PermissionEnum.Read" id="option-two-@(i)" />
                            }
                            <label class="permission-label" for="option-two-@(i)">Lezen</label>


                            @if (Model.CurrentPermissions != null && Model.CurrentPermissions.HasPermission("Write" + Model.Permissions[i].Step.Name))
                            {
                                <input asp-for="@Model.Permissions[i].Permission" type="radio" value="@StepPermission.PermissionEnum.Write" id="option-three-@(i)" checked />
                            }
                            else
                            {
                                <input asp-for="@Model.Permissions[i].Permission" type="radio" value="@StepPermission.PermissionEnum.Write" id="option-three-@(i)" />
                            }
                            <label class="permission-label" for="option-three-@(i)">Schrijven</label>
                        </div>
                    </td>
                </tr>
            }
        <tr>
            <td>Is project manager</td>
            <td>
                <div class="radio-group">
                    @if (Model.IsProjectLeader)
                    {
                        <input asp-for="@Model.IsProjectLeader" type="radio" id="option-one-99" value="true" checked>
                        <label class="permission-label" for="option-one-99">Ja</label>
                        <input asp-for="@Model.IsProjectLeader" type="radio" id="option-two-99" value="false">
                        <label class="permission-label" for="option-two-99">Nee</label>
                    }
                    else
                    {
                        <input asp-for="@Model.IsProjectLeader" type="radio" id="option-one-99" value="true">
                        <label class="permission-label" for="option-one-99">Ja</label>
                        <input asp-for="@Model.IsProjectLeader" type="radio" id="option-two-99" value="false" checked>
                        <label class="permission-label" for="option-two-99">Nee</label>
                    }
                </div>
            </td>
            
        </tr>
        </tbody>
    </table>
    <button value="submit" class="btn btn-success">Opslaan</button>
</form>
</div>